package colorx

import (
	"fmt"
	"testing"
)

func Test_Str(t *testing.T) {
	fmt.Println(Cyan("hello world"))
	fmt.Println(Cyan(1))
	fmt.Println(Cyan(0.1))
	fmt.Println(Cyan(false))
	fmt.Println("===========")
	fmt.Println(Green("hello world"))
	fmt.Println(Green(1))
	fmt.Println(Green(0.1))
	fmt.Println(Green(false))
	fmt.Println("==============")
	fmt.Println(White("hello world"))
	fmt.Println(White(1))
	fmt.Println(White(0.1))
	fmt.Println(White(false))
	fmt.Println("==============")
	fmt.Println(Yellow("hello world"))
	fmt.Println(Yellow(1))
	fmt.Println(Yellow(0.1))
	fmt.Println(Yellow(false))
	fmt.Println("==============")
	fmt.Println(Red("hello world"))
	fmt.Println(Red(1))
	fmt.Println(Red(0.1))
	fmt.Println(Red(false))
	fmt.Println("==============")
	fmt.Println(Magenta("hello world"))
	fmt.Println(Magenta(1))
	fmt.Println(Magenta(0.1))
	fmt.Println(Magenta(false))
	fmt.Println("==============")
	fmt.Println(Blue("hello world"))
	fmt.Println(Blue(1))
	fmt.Println(Blue(0.1))
	fmt.Println(Blue(false))
	fmt.Println("==============")
}

func Test_Printf(t *testing.T) {
	CyanPf("hello world")
	CyanPf(1)
	CyanPf(0.1)
	CyanPf(false)
	GreenPf("hello world")
	GreenPf(1)
	GreenPf(0.1)
	GreenPf(false)
	WhitePf("hello world")
	WhitePf(1)
	WhitePf(0.1)
	WhitePf(false)
	YellowPf("hello world")
	YellowPf(1)
	YellowPf(0.1)
	YellowPf(false)
	RedPf("hello world")
	RedPf(1)
	RedPf(0.1)
	RedPf(false)
	MagentaPf("hello world")
	MagentaPf(1)
	MagentaPf(0.1)
	MagentaPf(false)
	BluePf("hello world")
	BluePf(1)
	BluePf(0.1)
	BluePf(false)
}

func Test_Println(t *testing.T) {
	CyanPln("hello world")
	CyanPln(1)
	CyanPln(0.1)
	CyanPln(false)
	GreenPln("hello world")
	GreenPln(1)
	GreenPln(0.1)
	GreenPln(false)
	WhitePln("hello world")
	WhitePln(1)
	WhitePln(0.1)
	WhitePln(false)
	YellowPln("hello world")
	YellowPln(1)
	YellowPln(0.1)
	YellowPln(false)
	RedPln("hello world")
	RedPln(1)
	RedPln(0.1)
	RedPln(false)
	MagentaPln("hello world")
	MagentaPln(1)
	MagentaPln(0.1)
	MagentaPln(false)
	BluePln("hello world")
	BluePln(1)
	BluePln(0.1)
	BluePln(false)
}
