// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/burst.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BurstType int32

const (
	// 初始化
	BurstType_INIT BurstType = 0
	// 关闭
	BurstType_CLOSE BurstType = 1
)

var BurstType_name = map[int32]string{
	0: "INIT",
	1: "CLOSE",
}

var BurstType_value = map[string]int32{
	"INIT":  0,
	"CLOSE": 1,
}

func (x BurstType) String() string {
	return proto.EnumName(BurstType_name, int32(x))
}

func (BurstType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_187b98f11cb75ff0, []int{0}
}

type BurstMessage struct {
	Type                 BurstType         `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.BurstType" json:"type,omitempty"`
	Header               map[string]string `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 []byte            `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BurstMessage) Reset()         { *m = BurstMessage{} }
func (m *BurstMessage) String() string { return proto.CompactTextString(m) }
func (*BurstMessage) ProtoMessage()    {}
func (*BurstMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_187b98f11cb75ff0, []int{0}
}

func (m *BurstMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurstMessage.Unmarshal(m, b)
}
func (m *BurstMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurstMessage.Marshal(b, m, deterministic)
}
func (m *BurstMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurstMessage.Merge(m, src)
}
func (m *BurstMessage) XXX_Size() int {
	return xxx_messageInfo_BurstMessage.Size(m)
}
func (m *BurstMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BurstMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BurstMessage proto.InternalMessageInfo

func (m *BurstMessage) GetType() BurstType {
	if m != nil {
		return m.Type
	}
	return BurstType_INIT
}

func (m *BurstMessage) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BurstMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.BurstType", BurstType_name, BurstType_value)
	proto.RegisterType((*BurstMessage)(nil), "protocol.BurstMessage")
	proto.RegisterMapType((map[string]string)(nil), "protocol.BurstMessage.HeaderEntry")
}

func init() { proto.RegisterFile("protocol/burst.proto", fileDescriptor_187b98f11cb75ff0) }

var fileDescriptor_187b98f11cb75ff0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x4f, 0x2a, 0x2d, 0x2a, 0x2e, 0xd1, 0x03, 0x73, 0x85, 0x38, 0x60,
	0xa2, 0x4a, 0x87, 0x18, 0xb9, 0x78, 0x9c, 0x40, 0x32, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9,
	0x42, 0xea, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x7c, 0x46, 0xc2,
	0x7a, 0x30, 0x95, 0x7a, 0x60, 0x55, 0x21, 0x95, 0x05, 0xa9, 0x41, 0x60, 0x05, 0x42, 0x56, 0x5c,
	0x6c, 0x19, 0xa9, 0x89, 0x29, 0xa9, 0x45, 0x12, 0x4c, 0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x4a, 0x68,
	0x4a, 0xa1, 0x06, 0xea, 0x79, 0x80, 0x15, 0xb9, 0xe6, 0x95, 0x14, 0x55, 0x06, 0x41, 0x75, 0x08,
	0x09, 0x71, 0xb1, 0xa4, 0x24, 0x96, 0x24, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x04, 0x81, 0xd9,
	0x52, 0x96, 0x5c, 0xdc, 0x48, 0x4a, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0xc1, 0xce, 0xe0,
	0x0c, 0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x62,
	0x10, 0x8e, 0x15, 0x93, 0x05, 0xa3, 0x96, 0x02, 0x17, 0x27, 0xdc, 0x75, 0x42, 0x1c, 0x5c, 0x2c,
	0x9e, 0x7e, 0x9e, 0x21, 0x02, 0x0c, 0x42, 0x9c, 0x5c, 0xac, 0xce, 0x3e, 0xfe, 0xc1, 0xae, 0x02,
	0x8c, 0x4e, 0x92, 0x5c, 0x7c, 0x48, 0xfe, 0x4f, 0xce, 0xcf, 0x71, 0x62, 0x05, 0xeb, 0x08, 0x60,
	0x4c, 0x62, 0x03, 0x0b, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x03, 0x6a, 0xc2, 0xbf, 0x2a,
	0x01, 0x00, 0x00,
}
