// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/burst.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BurstType int32

const (
	// 添加代理信息
	BurstType_ADD_PROXY_INFO BurstType = 0
	// 关闭
	BurstType_CLOSE BurstType = 1
	// 客户连接
	BurstType_USER_CONNECT BurstType = 2
	// 转发数据
	BurstType_FORWARD_DATA BurstType = 3
)

var BurstType_name = map[int32]string{
	0: "ADD_PROXY_INFO",
	1: "CLOSE",
	2: "USER_CONNECT",
	3: "FORWARD_DATA",
}

var BurstType_value = map[string]int32{
	"ADD_PROXY_INFO": 0,
	"CLOSE":          1,
	"USER_CONNECT":   2,
	"FORWARD_DATA":   3,
}

func (x BurstType) String() string {
	return proto.EnumName(BurstType_name, int32(x))
}

func (BurstType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_187b98f11cb75ff0, []int{0}
}

type Headers int32

const (
	// 错误信息 string
	Headers_ERROR Headers = 0
	// port mapping Map<int,int>
	Headers_PORTS Headers = 1
	// 服务端暴露的端口 int32
	Headers_SERVER_EXPORT_PORT Headers = 2
	// 外网客户的id string
	Headers_USER_CONNECT_ID Headers = 3
	// register token string
	Headers_TOKEN Headers = 4
)

var Headers_name = map[int32]string{
	0: "ERROR",
	1: "PORTS",
	2: "SERVER_EXPORT_PORT",
	3: "USER_CONNECT_ID",
	4: "TOKEN",
}

var Headers_value = map[string]int32{
	"ERROR":              0,
	"PORTS":              1,
	"SERVER_EXPORT_PORT": 2,
	"USER_CONNECT_ID":    3,
	"TOKEN":              4,
}

func (x Headers) String() string {
	return proto.EnumName(Headers_name, int32(x))
}

func (Headers) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_187b98f11cb75ff0, []int{1}
}

type BurstMessage struct {
	Type                 BurstType          `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.BurstType" json:"type,omitempty"`
	Header               map[int32]*any.Any `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Data                 []byte             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BurstMessage) Reset()         { *m = BurstMessage{} }
func (m *BurstMessage) String() string { return proto.CompactTextString(m) }
func (*BurstMessage) ProtoMessage()    {}
func (*BurstMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_187b98f11cb75ff0, []int{0}
}

func (m *BurstMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BurstMessage.Unmarshal(m, b)
}
func (m *BurstMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BurstMessage.Marshal(b, m, deterministic)
}
func (m *BurstMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BurstMessage.Merge(m, src)
}
func (m *BurstMessage) XXX_Size() int {
	return xxx_messageInfo_BurstMessage.Size(m)
}
func (m *BurstMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BurstMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BurstMessage proto.InternalMessageInfo

func (m *BurstMessage) GetType() BurstType {
	if m != nil {
		return m.Type
	}
	return BurstType_ADD_PROXY_INFO
}

func (m *BurstMessage) GetHeader() map[int32]*any.Any {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BurstMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Proxy struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proxy) Reset()         { *m = Proxy{} }
func (m *Proxy) String() string { return proto.CompactTextString(m) }
func (*Proxy) ProtoMessage()    {}
func (*Proxy) Descriptor() ([]byte, []int) {
	return fileDescriptor_187b98f11cb75ff0, []int{1}
}

func (m *Proxy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proxy.Unmarshal(m, b)
}
func (m *Proxy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proxy.Marshal(b, m, deterministic)
}
func (m *Proxy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proxy.Merge(m, src)
}
func (m *Proxy) XXX_Size() int {
	return xxx_messageInfo_Proxy.Size(m)
}
func (m *Proxy) XXX_DiscardUnknown() {
	xxx_messageInfo_Proxy.DiscardUnknown(m)
}

var xxx_messageInfo_Proxy proto.InternalMessageInfo

func (m *Proxy) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Proxy) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Ports struct {
	Ports                map[int32]*Proxy `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Ports) Reset()         { *m = Ports{} }
func (m *Ports) String() string { return proto.CompactTextString(m) }
func (*Ports) ProtoMessage()    {}
func (*Ports) Descriptor() ([]byte, []int) {
	return fileDescriptor_187b98f11cb75ff0, []int{2}
}

func (m *Ports) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ports.Unmarshal(m, b)
}
func (m *Ports) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ports.Marshal(b, m, deterministic)
}
func (m *Ports) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ports.Merge(m, src)
}
func (m *Ports) XXX_Size() int {
	return xxx_messageInfo_Ports.Size(m)
}
func (m *Ports) XXX_DiscardUnknown() {
	xxx_messageInfo_Ports.DiscardUnknown(m)
}

var xxx_messageInfo_Ports proto.InternalMessageInfo

func (m *Ports) GetPorts() map[int32]*Proxy {
	if m != nil {
		return m.Ports
	}
	return nil
}

func init() {
	proto.RegisterEnum("protocol.BurstType", BurstType_name, BurstType_value)
	proto.RegisterEnum("protocol.Headers", Headers_name, Headers_value)
	proto.RegisterType((*BurstMessage)(nil), "protocol.BurstMessage")
	proto.RegisterMapType((map[int32]*any.Any)(nil), "protocol.BurstMessage.HeaderEntry")
	proto.RegisterType((*Proxy)(nil), "protocol.Proxy")
	proto.RegisterType((*Ports)(nil), "protocol.Ports")
	proto.RegisterMapType((map[int32]*Proxy)(nil), "protocol.Ports.PortsEntry")
}

func init() { proto.RegisterFile("protocol/burst.proto", fileDescriptor_187b98f11cb75ff0) }

var fileDescriptor_187b98f11cb75ff0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x51, 0x8b, 0xd3, 0x40,
	0x14, 0x85, 0x9d, 0xa4, 0x59, 0xed, 0x6d, 0xe9, 0x0e, 0xb3, 0x8b, 0x64, 0xfb, 0x54, 0x0a, 0x62,
	0xa9, 0x90, 0x4a, 0x7d, 0x91, 0x7d, 0x4b, 0x9b, 0x59, 0x2c, 0x6a, 0x26, 0xdc, 0x46, 0x77, 0x7d,
	0x0a, 0xe9, 0xee, 0x58, 0x17, 0x43, 0x27, 0x24, 0xa9, 0x98, 0x77, 0x7f, 0xa4, 0x3f, 0x47, 0x66,
	0xb2, 0xb5, 0x51, 0xf6, 0x65, 0xb8, 0x39, 0xf9, 0xee, 0xc9, 0x39, 0x43, 0xe0, 0x3c, 0x2f, 0x54,
	0xa5, 0x6e, 0x55, 0x36, 0xdb, 0xec, 0x8b, 0xb2, 0xf2, 0xcc, 0x23, 0x7b, 0x76, 0x50, 0x87, 0x17,
	0x5b, 0xa5, 0xb6, 0x99, 0x9c, 0x19, 0x61, 0xb3, 0xff, 0x3a, 0x4b, 0x77, 0x75, 0x03, 0x8d, 0x7f,
	0x13, 0xe8, 0x2f, 0xf4, 0xd2, 0x47, 0x59, 0x96, 0xe9, 0x56, 0xb2, 0x97, 0xd0, 0xa9, 0xea, 0x5c,
	0xba, 0x64, 0x44, 0x26, 0x83, 0xf9, 0x99, 0x77, 0x30, 0xf1, 0x0c, 0x15, 0xd7, 0xb9, 0x44, 0x03,
	0xb0, 0x4b, 0x38, 0xf9, 0x26, 0xd3, 0x3b, 0x59, 0xb8, 0xd6, 0xc8, 0x9e, 0xf4, 0xe6, 0xe3, 0xff,
	0xd0, 0x07, 0x43, 0xef, 0x9d, 0x81, 0xf8, 0xae, 0x2a, 0x6a, 0x7c, 0xd8, 0x60, 0x0c, 0x3a, 0x77,
	0x69, 0x95, 0xba, 0xf6, 0x88, 0x4c, 0xfa, 0x68, 0xe6, 0xa1, 0x80, 0x5e, 0x0b, 0x65, 0x14, 0xec,
	0xef, 0xb2, 0x36, 0x31, 0x1c, 0xd4, 0x23, 0x9b, 0x82, 0xf3, 0x23, 0xcd, 0xf6, 0xd2, 0xb5, 0x46,
	0x64, 0xd2, 0x9b, 0x9f, 0x7b, 0x4d, 0x2b, 0xef, 0xd0, 0xca, 0xf3, 0x77, 0x35, 0x36, 0xc8, 0xa5,
	0xf5, 0x96, 0x8c, 0x5f, 0x81, 0x13, 0x15, 0xea, 0x67, 0xcd, 0x06, 0x60, 0xdd, 0xe7, 0xc6, 0xa9,
	0x8b, 0xd6, 0x7d, 0xae, 0xbf, 0x9e, 0xab, 0xa2, 0x32, 0x3e, 0x0e, 0x9a, 0x79, 0xfc, 0x8b, 0x80,
	0x13, 0xa9, 0xa2, 0x2a, 0xd9, 0x6b, 0x70, 0xb4, 0x52, 0xba, 0xc4, 0xd4, 0x1a, 0x1e, 0x6b, 0x99,
	0xf7, 0xcd, 0xd9, 0xd4, 0x69, 0xc0, 0xe1, 0x0a, 0xe0, 0x28, 0x3e, 0x12, 0xfc, 0xc5, 0xbf, 0xc1,
	0x4f, 0x5b, 0x8e, 0x3a, 0x5f, 0x2b, 0xf3, 0x34, 0x84, 0xee, 0xdf, 0x7b, 0x66, 0x0c, 0x06, 0x7e,
	0x10, 0x24, 0x11, 0x8a, 0x9b, 0x2f, 0xc9, 0x2a, 0xbc, 0x12, 0xf4, 0x09, 0xeb, 0x82, 0xb3, 0xfc,
	0x20, 0xd6, 0x9c, 0x12, 0x46, 0xa1, 0xff, 0x69, 0xcd, 0x31, 0x59, 0x8a, 0x30, 0xe4, 0xcb, 0x98,
	0x5a, 0x5a, 0xb9, 0x12, 0x78, 0xed, 0x63, 0x90, 0x04, 0x7e, 0xec, 0x53, 0x7b, 0x7a, 0x0d, 0x4f,
	0x9b, 0x4b, 0x2d, 0xf5, 0x26, 0x47, 0x14, 0xd8, 0x98, 0x44, 0x02, 0xe3, 0x35, 0x25, 0xec, 0x39,
	0xb0, 0x35, 0xc7, 0xcf, 0x1c, 0x13, 0x7e, 0xa3, 0xb5, 0x44, 0x1f, 0xd4, 0x62, 0x67, 0x70, 0xda,
	0x36, 0x4f, 0x56, 0x01, 0xb5, 0xf5, 0x5e, 0x2c, 0xde, 0xf3, 0x90, 0x76, 0x16, 0x17, 0x30, 0x68,
	0xfd, 0x6b, 0xb7, 0x2a, 0x5b, 0x38, 0x26, 0x78, 0x44, 0x36, 0x27, 0x46, 0x7a, 0xf3, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x91, 0x69, 0x6e, 0xbd, 0x96, 0x02, 0x00, 0x00,
}
