// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/burst.proto

package burst.protocol;

public interface BurstMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.BurstMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.protocol.BurstType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.protocol.BurstType type = 1;</code>
   * @return The type.
   */
  burst.protocol.BurstType getType();

  /**
   * <code>map&lt;int32, .google.protobuf.Any&gt; header = 2;</code>
   */
  int getHeaderCount();
  /**
   * <code>map&lt;int32, .google.protobuf.Any&gt; header = 2;</code>
   */
  boolean containsHeader(
      int key);
  /**
   * Use {@link #getHeaderMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.google.protobuf.Any>
  getHeader();
  /**
   * <code>map&lt;int32, .google.protobuf.Any&gt; header = 2;</code>
   */
  java.util.Map<java.lang.Integer, com.google.protobuf.Any>
  getHeaderMap();
  /**
   * <code>map&lt;int32, .google.protobuf.Any&gt; header = 2;</code>
   */

  com.google.protobuf.Any getHeaderOrDefault(
      int key,
      com.google.protobuf.Any defaultValue);
  /**
   * <code>map&lt;int32, .google.protobuf.Any&gt; header = 2;</code>
   */

  com.google.protobuf.Any getHeaderOrThrow(
      int key);

  /**
   * <code>bytes data = 3;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   * 当type = REMOVE_PROXY_INFO 时有效
   * </pre>
   *
   * <code>repeated int32 serverPort = 4;</code>
   * @return A list containing the serverPort.
   */
  java.util.List<java.lang.Integer> getServerPortList();
  /**
   * <pre>
   * 当type = REMOVE_PROXY_INFO 时有效
   * </pre>
   *
   * <code>repeated int32 serverPort = 4;</code>
   * @return The count of serverPort.
   */
  int getServerPortCount();
  /**
   * <pre>
   * 当type = REMOVE_PROXY_INFO 时有效
   * </pre>
   *
   * <code>repeated int32 serverPort = 4;</code>
   * @param index The index of the element to return.
   * @return The serverPort at the given index.
   */
  int getServerPort(int index);
}
