// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/burst.proto

package burst.protocol;

public final class Burst {
  private Burst() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_BurstMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_BurstMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_BurstMessage_HeaderEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_BurstMessage_HeaderEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Proxy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Proxy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Ports_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Ports_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_Ports_PortsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_Ports_PortsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024protocol/burst.proto\022\010protocol\032\031google" +
      "/protobuf/any.proto\"\314\001\n\014BurstMessage\022!\n\004" +
      "type\030\001 \001(\0162\023.protocol.BurstType\0222\n\006heade" +
      "r\030\002 \003(\0132\".protocol.BurstMessage.HeaderEn" +
      "try\022\014\n\004data\030\003 \001(\014\022\022\n\nserverPort\030\004 \003(\005\032C\n" +
      "\013HeaderEntry\022\013\n\003key\030\001 \001(\005\022#\n\005value\030\002 \001(\013" +
      "2\024.google.protobuf.Any:\0028\001\"[\n\005Proxy\022\n\n\002i" +
      "p\030\001 \001(\t\022\014\n\004port\030\002 \001(\005\022\014\n\004type\030\003 \001(\t\022\024\n\014c" +
      "ustomDomain\030\004 \001(\t\022\024\n\014serverExport\030\005 \001(\005\"" +
      "q\n\005Ports\022)\n\005ports\030\001 \003(\0132\032.protocol.Ports" +
      ".PortsEntry\032=\n\nPortsEntry\022\013\n\003key\030\001 \001(\005\022\036" +
      "\n\005value\030\002 \001(\0132\017.protocol.Proxy:\0028\001*e\n\tBu" +
      "rstType\022\022\n\016ADD_PROXY_INFO\020\000\022\t\n\005CLOSE\020\001\022\020" +
      "\n\014USER_CONNECT\020\002\022\020\n\014FORWARD_DATA\020\003\022\025\n\021RE" +
      "MOVE_PROXY_INFO\020\004*j\n\007Headers\022\t\n\005ERROR\020\000\022" +
      "\t\n\005PORTS\020\001\022\026\n\022SERVER_EXPORT_PORT\020\002\022\023\n\017US" +
      "ER_CONNECT_ID\020\003\022\t\n\005TOKEN\020\004\022\021\n\rCUSTOM_DOM" +
      "AIN\020\005B)\n\016burst.protocolB\005BurstP\001Z\016burst." +
      "protocolb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_protocol_BurstMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_BurstMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_BurstMessage_descriptor,
        new java.lang.String[] { "Type", "Header", "Data", "ServerPort", });
    internal_static_protocol_BurstMessage_HeaderEntry_descriptor =
      internal_static_protocol_BurstMessage_descriptor.getNestedTypes().get(0);
    internal_static_protocol_BurstMessage_HeaderEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_BurstMessage_HeaderEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protocol_Proxy_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_Proxy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Proxy_descriptor,
        new java.lang.String[] { "Ip", "Port", "Type", "CustomDomain", "ServerExport", });
    internal_static_protocol_Ports_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_Ports_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Ports_descriptor,
        new java.lang.String[] { "Ports", });
    internal_static_protocol_Ports_PortsEntry_descriptor =
      internal_static_protocol_Ports_descriptor.getNestedTypes().get(0);
    internal_static_protocol_Ports_PortsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_Ports_PortsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
