// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/burst.proto

package burst.protocol;

public interface PortsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Ports)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, int32&gt; ports = 1;</code>
   */
  int getPortsCount();
  /**
   * <code>map&lt;int32, int32&gt; ports = 1;</code>
   */
  boolean containsPorts(
      int key);
  /**
   * Use {@link #getPortsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getPorts();
  /**
   * <code>map&lt;int32, int32&gt; ports = 1;</code>
   */
  java.util.Map<java.lang.Integer, java.lang.Integer>
  getPortsMap();
  /**
   * <code>map&lt;int32, int32&gt; ports = 1;</code>
   */

  int getPortsOrDefault(
      int key,
      int defaultValue);
  /**
   * <code>map&lt;int32, int32&gt; ports = 1;</code>
   */

  int getPortsOrThrow(
      int key);
}
