// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/burst.proto

package burst.protocol;

public interface PortsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Ports)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, .protocol.Proxy&gt; ports = 1;</code>
   */
  int getPortsCount();
  /**
   * <code>map&lt;int32, .protocol.Proxy&gt; ports = 1;</code>
   */
  boolean containsPorts(
      int key);
  /**
   * Use {@link #getPortsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, burst.protocol.Proxy>
  getPorts();
  /**
   * <code>map&lt;int32, .protocol.Proxy&gt; ports = 1;</code>
   */
  java.util.Map<java.lang.Integer, burst.protocol.Proxy>
  getPortsMap();
  /**
   * <code>map&lt;int32, .protocol.Proxy&gt; ports = 1;</code>
   */

  burst.protocol.Proxy getPortsOrDefault(
      int key,
      burst.protocol.Proxy defaultValue);
  /**
   * <code>map&lt;int32, .protocol.Proxy&gt; ports = 1;</code>
   */

  burst.protocol.Proxy getPortsOrThrow(
      int key);
}
