// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/burst.proto

package burst.protocol;

public interface ProxyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Proxy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>string type = 3;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string customDomain = 4;</code>
   */
  java.lang.String getCustomDomain();
  /**
   * <code>string customDomain = 4;</code>
   */
  com.google.protobuf.ByteString
      getCustomDomainBytes();

  /**
   * <code>int32 serverExport = 5;</code>
   */
  int getServerExport();
}
