// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/burst.proto

package burst.protocol;

public interface ProxyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.Proxy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();
}
