// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	proxy "github.com/fzdwx/burst/server/internal/handler/proxy"
	user "github.com/fzdwx/burst/server/internal/handler/user"
	"github.com/fzdwx/burst/server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: user.AuthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/user,"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add/:token",
				Handler: proxy.AddProxyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/remove",
				Handler: proxy.RemoveProxyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/proxy"),
	)
}
