// Code generated by goctl. DO NOT EDIT.
package types

type RegisterResp struct {
	Token string `json:"the access token"`
}

type ClientConnectReq struct {
	Token string `path:"token"`
}

type ClientConnectResp struct {
	Message string `json:"message"`
}
